greatscottgadgets/packetry

- src/capture.rs
- src/main.rs
The only work still needed in the `finish` method was to add an entry to the endpoint’s transfer index, if a transfer was left in progress at the end of capture.
This step is moved to `transfer_start`, the `finish` method is removed, and `ep_transfer_end` is merged into `transfer_end`.
> Remove finish method

- src/capture.rs
- src/main.rs
This turned out to be fairly simple. We can just replace the `TreeExpander` with a generic `Expander`, show or hide it according to  `TreeListRow::is_expandable`, and connect its expansion to `TreeListRow::set_expanded`.
This fixes the duplicate indent that was being added by `TreeExpander`.
I've adjusted the connecting lines so that they line up with the expander widgets. It's not a perfect match, but I guess it'll do until we have a graphical version of the connecting lines.
> Replace use of TreeExpander

- src/capture.rs
This PR stacks on #18 and adds interpretation within the decode loop for:
1. `GetDescriptor` requests that successfully read:
- Device descriptors
- Configuration descriptors, including:
- Interface descriptors, including:
- Endpoint descriptors
2. `SetConfiguration` requests that change a device configuration.
The latest read copies of all these descriptors are stored in a hierarchy of the form:
```
device -> configuration -> interface -> endpoint
```
Once both a `GetDescriptor` request for a configuration and a `SetConfiguration` request for that configuration have been captured, the endpoint types `Bulk`, `Isochronous` or `Interrupt` are assigned to endpoints  as specified in the active configuration. Endpoints for which we do not yet have a confirmed identification are labelled as …
> Decode descriptors to correctly identify endpoint types

- src/capture.rs
- src/main.rs
- src/model/imp.rs
- src/model/mod.rs
- src/row_data/imp.rs
- src/row_data/mod.rs
This PR stacks on #18 and #20, and adds a side pane showing the descriptor hierarchy as captured from requests seen.
I wanted to avoid duplicating all the UI and GObject boilerplate for a second ListView/TreeListModel, so I've tried to genericise and reuse that as much as possible, but there's still some repetition because of the need to have concrete types at the Rust/GObject boundary.
> Add side pane showing device/configuration/interface/endpoint hierarchy.

- src/capture.rs
- src/decoder.rs
- src/main.rs
- src/model/imp.rs
- src/model/mod.rs
- src/row_data/mod.rs
- src/usb.rs
This replaces #28 and does `Result`-based error handling everywhere. Most methods on `Capture` and `Decoder` now return a `Result<_, CaptureError>`. All uses of `unwrap` outside of tests have been removed.
Since the code makes heavy use of complicated indexing schemes, another likely source of panics was out-of-bound accesses to arrays. So I have made all array access use the `get` and `get_mut` methods, returning an `IndexError` if out-of-bounds. I have made a few exceptions to this where very obviously safe.
The error handling currently effectively stops at the Rust/GObject boundary. Where possible, errors are passed on to the UI, e.g. an error in `get_summary` results in the error text appearing where the summary would go. In other cases however the APIs involved do not allow an easy …
> Error handling

- src/capture.rs
- src/decoder.rs
- src/file_vec.rs
- src/hybrid_index.rs
- src/id.rs
- src/main.rs
- src/usb.rs
- src/vec_map.rs
This PR builds on the work in #33. The common theme is to make better use of the Rust type system in order to streamline the code in the `capture` & `decoder` modules and, more generally, to write better Rust.
The main changes include:
- Add further types to the `usb` module to encapsulate more conversion and formatting details. These include `EndpointAddr`, `EndpointType`, `StringId`, `BCDVersion`, `UTF16Bytes` and `UTF16ByteVec`.
- Add a `VecMap<K, V>` type to use in place of `Vec`. This has two key properties:
- Indices can be of a specific newtype, converted to `usize` internally. This removes a lot of `x as usize` conversions in the code.
- Items can be inserted at a specific index, with the underlying `Vec<Option<V>>` being enlarged as necessary. This removes several places where we …
> Further improvements to types and Rust usage in capture & decoder modules

- .github/workflows/rust.yml
- src/capture.rs
- src/decoder.rs
- src/file_vec.rs
- src/tree_list_model.rs
- src/usb.rs
This fixes a handful of Clippy warnings that were introduced by a new Rust version.
For most of them, I've implemented the suggested fix.
For the [type_complexity](https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity) warning, I tried to break out part of it as a new `type` but ran into a problem where it needed an unstable feature for inherent associated types, so I've just squelched that warning.
The other commit sets the workflow to run every week as we have on most of the other repos, so we can spot issues like this sooner. It should also allow for the workflow to be triggered manually.
> Clippy & CI fixes

- src/expander/mod.rs
- src/main.rs
Reduce minimum size parameters for the two view panes, and set `pango::EllipsizeMode` so that text is truncated nicely as the window shrinks.
> Handle narrow window sizes better

- src/capture.rs
- src/decoder.rs
- src/id.rs
- src/main.rs
- src/row_data/imp.rs
- src/row_data/mod.rs
- src/tree_list_model.rs
Two changes here:
1. We use `IndexError` as a catch-all for any lookup failure in `Capture`. Make it take a string argument to indicate the cause, and add suitable strings at all call sites.
2. When lookup for an individual tree node fails, display the error in the view rather than crashing.
> Improve error reporting

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/capture.rs
- src/main.rs
Currently we use the [pcap](https://crates.io/crates/pcap) crate to read pcap files, which uses the `libpcap` library internally.
We only need the capability to read (and at some point write) pcap files, but that crate also provides the rest of the API, including its functionality for sniffing network devices. Satisfying the build dependencies requires some extra steps for users, particularly on Windows, where the `pcap` crate needs to link against [Npcap](https://npcap.com/)'s `wpcap` library.
Since we only need the file format capabilities, this PR switches to using the [pcap-file](https://crates.io/crates/pcap-file) crate, which provides a native Rust implementation of the file format without those external dependencies.
This PR is against current `main` but there is a version on my …
> Switch from pcap to pcap-file to avoid libpcap/wpcap dependency.

- src/main.rs
PR #45 introduced a performance regression, because `PcapReader` doesn't internally buffer the `Read` implementation that it wraps. This fixes that by wrapping a `BufReader` around the `File`.
> Use a BufReader for pcap file.

- src/file_vec.rs
- src/id.rs
Just some places where we were casting a value to u64 that already was.
> Fixes for new Clippy errors introduced by Rust 1.66.

- .github/workflows/rust.yml
This PR uses the [rust-cache](https://github.com/marketplace/actions/rust-cache) and [cache-apt-packages](https://github.com/marketplace/actions/cache-apt-packages) actions to speed up our CI workflow by preloading the Rust toolchain, the installed Debian packages for the Ubuntu runner, and all Rust dependencies built with Cargo. The actions used are already set up to use sensible caching policies for the items in question, so the cache should be invalidated as needed when dependency versions change.
Before ([build](https://github.com/greatscottgadgets/packetry/actions/runs/3709423685/usage) of #52):
After ([build of same change](https://github.com/martinling/packetry/actions/runs/3709779406/usage), appended to this PR):
> Cache dependencies to speed up CI

- .github/workflows/rust.yml
Workaround for https://github.com/awalsh128/cache-apt-pkgs-action/issues/82.
This just bumps the cache version which is all we need to do; the broken release was already reverted.
> CI: Work around bug in cache-apt-pkgs-action

- src/main.rs
- src/model/mod.rs
This fixes new devices not appearing in the device tree pane during live capture.
> Update device tree during live update as well as traffic tree.

- src/capture.rs
- src/decoder.rs
- src/expander/mod.rs
- src/main.rs
- src/tree_list_model.rs
- src/usb.rs
Fixes new clippy errors introduced by Rust 1.67.
> Use variable names in format strings where possible

- Cargo.toml
- src/backend/luna.rs
- src/capture.rs
- src/decoder.rs
- src/main.rs
- src/usb.rs
This PR adds new UI features as follows:
1. Display product names in the device tree when known.
2. Run the decoder loop in its own thread.
3. Display a progress bar whilst loading a pcap file.
4. Add a header bar to the main window.
5. Clean up the construction of `Capture` and `Decoder` to make it simpler to reset to an empty capture.
6. Add open, save, capture and stop buttons to header bar.
7. Connect the capture and stop buttons to control LUNA capture.
8. Start a new empty `Capture` and reset UI when a new capture is started.
9. Connect the open button to start a file chooser and load a pcap file.
10. Connect the stop button to allow cancelling the ongoing loading of a pcap file.
11. Add a compile time optional feature that listens on a TCP port and blocks the decoder until a byte …
> UI features

- src/capture.rs
- src/decoder.rs
- src/main.rs
- src/model/mod.rs
- src/row_data/imp.rs
- src/row_data/mod.rs
- src/tree_list_model.rs
- tests/emf2022-badge/reference.txt
- tests/hackrf-connect/reference.txt
- tests/hackrf-dfu-enum/reference.txt
This PR focuses on mechanisms for updating the UI as new packets are added to a running capture. With these changes:
- Transfer descriptions are updated as transfers make progress.
- New transactions and packets are appended to parents that are expanded in the traffic view.
- New information is added to the device hierarchy tree as it becomes available.
This PR is part of the the planned sequence documented in #54. The next PR will focus on decoder changes to improve the display of partial transactions and transfers, and will add support for SPLIT transactions. This PR lays the groundwork, by establishing the necessary UI update mechanisms for the effects to be seen.
Note that to see the effects of individual packets on the view, captures can be replayed packet-by-packet by running …
> Additional live update mechanisms

- Cargo.lock
- Cargo.toml
- src/capture.rs
- src/main.rs
This PR adds support for saving a capture to a pcap file.
This can take a while for large captures, so saving runs the background with a progress bar and can be interrupted, using the same UI mechanisms as for loading a pcap file.
Note some limitations:
- This implementation saves all packets. The ability to select what to save will come in a future PR.
- Since we have no timestamping yet, all timestamps in the pcap file are set to zero.
> Add support for saving capture to a pcap file

- src/main.rs
Don't start periodic updates at startup. Instead, start them when beginning a capture, or beginning load/save. While saving, we need to continue updating despite the capture not changing, in order to update the progress bar.
> Fix logic for when to run UI update.

- .github/workflows/rust.yml
We were not explicitly installing pkg-config before, but getting it accidentally, and now we don't.
Add it to the brew dependencies to fix the build.
> CI: Add pkg-config to brew dependencies

- src/capture.rs
- src/usb.rs
- tests/split-enum/reference.txt
Tweak some item summaries:
- End items for control transfers included an unnecessary/inaccurate endpoint name in the summary e.g. `3.0 OUT`. Instead only specify the device address in the summary.
- Control transfers where the recipient is not a device, interface or endpoint, were identified as `for device X, index Y`, which is inaccurate and caused the index to be shown twice. Where the recipient field is `3` i.e. `Other`, just identify the request as being `on device X`.
> Summary fixes

- src/backend/luna.rs
This is necessary to ensure an error dialog rather than a panic, in the case where Packetry is run on a VirtualBox VM without USB forwarding.
In that scenario, `libusb_init()` returns an error, which is translated into a panic by rusb, since the API does not allow for returning a `Result` when `GlobalContext` is used.
> Open our own libusb context rather than using the global one

- src/backend/luna.rs
- src/ui.rs
This PR combines several changes to the UI.
- Rearrange toolbar as discussed in #68.
- Add a status bar.
- Add a device selector, and a button to scan for available devices.
- Provide a place to integrate @miek's work on detecting supported capture speeds, in `DeviceSelector::scan`.
Closes #9 and #68.
> UI rework: toolbar changes, status bar, device selector

- src/backend/luna.rs
- src/ui.rs
Based on #73 
This starts off with some refactoring to return a struct with device information from the backend `scan` function, moves querying the device name/description to the backend and returns it in the new struct, adds available speeds to the struct, adds an 'Auto' option, and finally supports the new vendor request to query the available speeds (to be added in https://github.com/greatscottgadgets/luna/pull/202).
> Add support for devices to report available analysis speeds

- src/ui.rs
This ensures UI startup is not blocked from completing by USB errors.
> Defer initial device scan to after UI startup

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/stream.rs
This PR adds a new lock-free implementation of the basic underlying data structure required by Packetry: an append-only data stream, backed by a file, for which we require fast random access to any part of the data whilst it continues to grow.
Packetry's current implementation, in the `FileVec` and `HybridIndex` types, uses file I/O which adds significant overhead. Both reading and writing require exclusive access to a stream object, which is currently managed by a single `Mutex` protecting the whole `Capture` database. This creates contention between the decoder and UI threads.
The new implementation creates two objects for each stream: a unique `StreamWriter`, and a clonable `StreamReader`. The writer and any number of readers may operate concurrently without blocking each other.
- …
> Lock-free stream implementation

- src/capture.rs
- src/compact_index.rs
- src/decoder.rs
- src/id.rs
- src/index_stream.rs
This PR fixes delays in the UI when summarizing control transfers with large numbers of transactions (e.g. many NAKs). These delays occurred because the `CaptureReader::control_transfer` method had to iterate over all transactions in the transfer to retrieve the payload data.
For data transfers, we already had a per-endpoint `data_index` mapping endpoint transaction IDs to byte counts, allowing payload data to be located efficiently. However this scheme depends on the fact that we include only the successful transactions in a data transfer, assigning transactions that result in a NAK into a polling group instead. For control transfers we group NAKed transactions with the transfer, so the same indexing scheme cannot be applied.
This PR replaces the existing `data_index` with two indexes, …
> Extend transfer data indexing to control transfers

- src/main.rs
This change stops GApplication from trying to have only a single shared instance of Packetry running at a time.
> Support multiple instances of the application

- .readthedocs.yaml
- Cargo.lock
- Cargo.toml
- src/backend/luna.rs
- src/capture.rs
- src/compact_index.rs
- src/data_stream.rs
- src/decoder.rs
- src/index_stream.rs
- src/model/mod.rs
- src/stream.rs
- src/tree_list_model.rs
- src/ui.rs
Use the [anyhow](https://docs.rs/anyhow/latest/anyhow/index.html) crate for error handling.
This crate provides:
- The `anyhow::Error` type, which wraps any other error type, and can thus replace the whole error type hierarchy we have currently including `PacketryError`, `CaptureError`, `StreamError`, `ModelError` etc.
- A `bail!` macro which can simplify sites where we just want to return an error with some text.
- A `Context` trait, implemented for `Option` and `Result`, which allows easily attaching context information when turning an existing `None` or `Err` value into an `anyhow::Error`. This neatly replaces some existing patterns and our `OnBug` trait.
As well as simplifying the code, this change enables us to display a backtrace for any error - this is implemented in the second …
> Use the `anyhow` crate for error handling

- src/backend/luna.rs
- src/ui.rs
A fix and some improvements following up on #82:
- Correctly handle the result of joining a capture worker thread, and displaying the message for a panic.
- Show the chain of causes behind an error.
- Don't attempt to show backtraces when not enabled.
> More error handling improvements

- README.md
- docs/source/introToPacketry.rst
- src/backend/cynthion.rs
- src/backend/mod.rs
- src/main.rs
- src/ui.rs
Just updating for [the name change](https://www.crowdsupply.com/great-scott-gadgets/luna/updates/renaming-luna-hardware-to-cynthion). No functional changes.
> Rename LUNA backend to Cynthion and update docs

- src/backend/cynthion.rs
- src/ui.rs
Depends on https://github.com/greatscottgadgets/cynthion/pull/87.
Updates how Packetry searches for and displays available Cynthion devices.
Changes are as follows:
1. Preliminary UI code cleanups.
2. Update available speeds when device selection is changed.
3. Name devices simply as `Cynthion`, unless duplicated, in which case disambiguate with serial number or bus/address.
4. Display all Cynthion devices found, including ones that cannot be used. For unusable devices, keep track of why.
5. Adjust methods to match https://github.com/greatscottgadgets/cynthion/pull/87
One detail I'm not sure of yet is how best to display the reasons for devices not being usable, but that doesn't have to be in this PR.
> Update for Cynthion analyzer USB API changes

- src/backend/cynthion.rs
This PR does a fair bit of refactoring of the Cynthion capture backend, in order to solve a quite simple problem.
The bug was that during shutdown, Packetry was tearing down the data transfer queue before sending the control request to stop capture. This meant that capture data which was flushed by the analyzer at stop time was lost. In most cases, this wasn't noticeable, but when using low-traffic devices (especially LS keyboards), a whole capture could be lost entirely, if it never produced the 512 bytes needed to fill a packet to the host.
Test case:
- Start a low speed capture.
- Plug in a USB LS keyboard.
- Stop capture.
- No traffic is captured.
To fix this there were basically two options:
1. Do a bunch more fiddly work to integrate the start/stop control requests into the same …
> Fix flushed capture data being missed at shutdown

- Cargo.toml
- src/backend/cynthion.rs
- src/capture.rs
- src/lib.rs
- src/test_cynthion.rs
This PR adds a hardware-in-the-loop test of Packetry's capture functionality, using a Cynthion device.
This test requires a Cynthion r0.6 or higher board, running analyzer gateware including the self-test device added in https://github.com/greatscottgadgets/cynthion/pull/98.
The host must be connected to both the CONTROL and TARGET-C ports. The TARGET-A port must be connected to the AUX port.
This test is optional and requires the `test-cynthion` feature to be enabled.
> Add hardware-in-the-loop test using Cynthion analyzer

- .github/workflows/rust.yml
The `rust-cache` action cuts down on compile times, but it keeps causing failures on the Mac builds because the cache brings along with it paths to libraries in specific versions of Homebrew packages, without which the final linking step fails.
If we could figure out a way to hash the Homebrew installation and use that as an additional key to the Rust cache, that would avoid this issue, but that doesn't seem straightforward.
So for now, remove this as it causes more trouble than it's worth.
> CI: Disable rust-cache action

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/test_replay.rs
This PR turns `test_replay` from a standalone, non-harness test into a normal unit test, that is part of the main binary target.
The reason this test was split out into a separate binary was that it calls into GTK, and on macOS, GTK can only be used from the main thread of a program. When `cargo test` is run, it runs tests in worker threads. Even if `--test-threads=1` is passed, it spawns a single worker thread, rather than running the tests on its main thread. So the replay test had to be written as a separate binary to ensure it executed on a main thread on macOS.
Making this test into a separate binary has caused other problems, though: we had to define a library crate, and a public API for it, just so that the main binary target and the test could share code. That wasn't an …
> Use procspawn crate to run replay test on macOS

- .github/workflows/rust.yml
Apparently when preparing #83 I had missed that you can set `VCPKG_INSTALLED_DIR` to choose where `run-vcpkg` will install to.
> Simplify vcpkg path usage

- src/backend/cynthion.rs
- src/ui.rs
This PR adds a warning bar that appears when a selected device is not usable for capture, and updates the reasons reported in the case of a protocol version mismatch.
> Add warning bar indicating why a selected device is unusable

- src/backend/cynthion.rs
- src/capture.rs
- src/decoder.rs
- src/loader.rs
- src/main.rs
- src/model/mod.rs
- src/test_cynthion.rs
- src/test_replay.rs
- src/tree_list_model.rs
- src/ui.rs
This PR adds timestamping to the Packetry UI, pcap file handling, and Cynthion backend.
- Bumps supported protocol version to `0x01`.
- Should be merged together with:
https://github.com/greatscottgadgets/cynthion/pull/104.
- The two PRs can be tested together via:
https://github.com/greatscottgadgets/cynthion-analyzer/pull/7
The hardware-in-the-loop test has been updated to test the new features.
Closes #6.
> Add timestamping

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- src/ui.rs
Our minimum supported Rust version (MSRV) is now 1.74.
This is imposed by the MSRV of recent versions of `nusb` - see https://github.com/kevinmehall/nusb/pull/62.
:ballot_box_with_check: Update the README and Cargo metadata to reflect this.
:ballot_box_with_check:  Fix CI testing of the MSRV, which was broken due to missing the `override: true` parameter for `actions-rs/toolchain`.
> Bump MSRV to 1.74, and fix MSRV testing in CI.

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/ui.rs
This PR adds a `--version` command line option, and an About dialog to the UI.
Version information is captured at compile time with the [git_version](https://docs.rs/git-version/latest/git_version/) macro, so that it is possible to identify builds from non-release versions.
The About dialog includes basic package information, the BSD license text for Packetry itself, and some system information: OS, architecture and GTK library version in use.
It does not yet include copyright or license information for any dependencies.
> Add `--version` option and About dialog

- .github/workflows/rust.yml
- wix/rust_licenses.py
Errors returned from `rust_licenses.py` were being ignored, because on Windows runners, commands are executed by PowerShell, and there's no equivalent of `set -e` there, so a multi-line `run` command will ignore errors as long as the last command in the sequence succeeds. This is documented [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference). What a footgun!
Fix this by forcing the shell to `bash` (thanks @miek for the tip), and then fix the underlying failure, which was that I hadn't added `BSD-2-Clause` to the list of accepted licenses when adding the `git-version` crate in #125. Also add `COPYING` to the list of filenames to check for a license in the crate source,  which is also needed to accept this …
> Fix failures in license scripts being lost

- Cargo.lock
- Cargo.toml
- src/build.rs
- src/main.rs
- src/ui.rs
- src/version.rs
- wix/rust_licenses.py
This PR uses the [`built`](https://docs.rs/built/latest/built/) crate to gather additional build-time information which is reported in the `--version` output and the About dialog.
Fixes the failure to build without a `.git` directory, caused by #125.
Output of `--version` when built with a `.git` directory:
```
Packetry version 0.1.0 (git b2029df)
Runtime information:
GTK version: 4.12.5
Packetry build information:
Git commit: b2029df15600f1ddcb2e0655b6baa0abfc6355cd
Cargo package version: 0.1.0
Enabled features: (none)
Rust compiler:
Version: rustc 1.79.0 (129f3b996 2024-06-10)
Target: x86_64-unknown-linux-gnu (little-endian, 64-bit)
Optimization level: 3
Debug build: no
```
Output when built without a `.git` directory:
```
Packetry version 0.1.0
Runtime information:
GTK version: 4.12.5 …
```
> Gather more build information and improve version string

- .github/workflows/rust.yml
- Update `actions/checkout` from v2/3 to v4
- Update `actions/upload-artifact` from v2 to v4
- Avoid conflicting artifacts by uploading only those from the `stable` Rust build.
- Replace unmaintained `actions-rs` actions with direct use of `rustup` and `cargo`.
- Always use the latest version of the Ubuntu runner.
- Replace deprecated `GabrielBB/xvfb-action` with direct use of `xvfb-run`.
- Don't try to install `pkg-config` on macOS; the runner has it.
> Update github actions to latest versions

- src/capture.rs
- src/main.rs
- src/pcap.rs
- src/test_cynthion.rs
- src/test_replay.rs
- src/ui.rs
Changes in this PR:
- Fix UI crashing with an underflow error when a non-existent filename is passed on the command line.
- Use the standard command line handling and file open mechanism for GTK applications.
- Previously we were doing our own command line processing in the `activate` callback.
- The correct method is to provide an `open` callback.
- Fixes a panic in `test_replay` when `--nocapture` was passed to the test and interpreted as a filename.
- Add information about command line options to the `Application` instance.
- This gets us a a useful `--help` output.
- Use the [`gio::File`](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/gio/struct.File.html) abstraction.
- This allows us to load and save files from anywhere that GIO knows how to access, such as SMB and MTP …
> Command line and file handling fixes

- Cargo.lock
- Cargo.toml
- src/usb.rs
- tests/analyzer-test-bad-cable/reference.txt
- tests/emf2022-badge/reference.txt
- tests/hackrf-connect/reference.txt
- tests/hackrf-dfu-enum/reference.txt
- tests/mouse/reference.txt
- tests/split-enum/reference.txt
- tests/ui/emf2022-badge/reference.txt
- tests/ui/mouse-step/reference.txt
I spotted that someone had written [this Rust crate](https://crates.io/crates/usb-ids) for the [Linux USB ID database](http://www.linux-usb.org/usb-ids.html), which gets us some easy quality of life improvements with very little code, e.g:
Recognition of vendor IDs, product IDs, and class/subclass/protocol values as seen in device and interface descriptors:
Recognition of language IDs in string descriptor requests:
This should also be helpful when we come to interpreting HID descriptors and traffic.
The crate used is under the MIT license, and the usb.ids database is under LGPL _or_ BSD-3-Clause.
> Use `usb.ids` database to interpret various ID values

- Cargo.lock
> Bump nusb version in Cargo.lock.

- src/ui.rs
Currently when you try to save a capture an error is thrown from GIO File info query since the pcap doesn't exist yet. I've moved the file info into the Load action to fix this and removed the ui.filename assignment as it doesn't seem to be needed for saving/reading.
> Fixed capture save not working

- src/ui.rs
Followup to these two PRs:
- #141
- #148
Changes in this PR:
- Use `replace` rather than `create` when saving files.
- Fixes #152.
- Move UI save and load routines into separate functions rather than one big closure (cleanup).
- Use the `basename` method to get a filename from a `gio::File` to show in the status bar, without relying on IO.
- Updating the status bar filename was disabled in #148.
- Fix GTK warnings due to invalid progress bar updates, when file size not yet known.
- This allows loading a file from an HTTPS URL to work cleanly.
- Cancel blocking `gio::File` operations if load/save is stopped by UI.
> Fixes for `gio::File` usage

- .github/workflows/appimage.yml
- .github/workflows/rust.yml
We had previously disabled the `rust-cache` action, because it could cause problems on macOS builds, where the latest GTK and dependencies are installed from Homebrew and it was possible for the cached Rust crate builds to end up pointing to library install paths that were no longer valid in the latest Homebrew install.
However, Windows is currently our slowest build platform, and our non-Rust dependency versions are fixed there by our choice of vcpkg commit ID, so by using this as a key to the rust-cache action, we can cache safely.
This cuts the Windows build time from 9m33s to 4m20s. Which is still the longest (Linux & macOS are around 3 mins each), but much less annoying.
> CI: Enable rust caching for Windows, if vcpkg dependencies unchanged.

- src/capture.rs
- src/usb.rs
- tests/ui/emf2022-badge/reference.txt
- tests/ui/mouse-step/reference.txt
The Endpoint summary line in the Interface descriptor list currently contains the address and direction data:
Endpoint 3 IN
This change adds the endpoint type too, as derived from the attribute data:
Endpoint 3 BULK IN
\- by defining std::fmt::Display for EndpointType, and using that in the summary data.
> ui: Add bulk/int/iso/cntl type to endpoint summary info

- src/ui.rs
When running tests we have an unused import:
warning: unused import: `self`
--> src/ui.rs:24:17
|
24 | use gtk::glib::{self, Object, SignalHandlerId};
|                 ^^^^
|
= note: `#[warn(unused_imports)]` on by default
The one use of the `self` import is not(cfg(test)); all other uses reference the full gtk::glib path.
Change the glib (::self) use to suit the non-test uses.
> test: remove unused import in test cfg

- src/test_cynthion.rs
Fixes some bugs in the HITL test:
- The `--save-captures` option was broken due to calling `File::open` rather than `File::create`.
- Fixes #158.
- Due to a bug in the SOF checking loop, only SOF packets up to the first bus reset were being counted.
- We were only checking for a small minimum of SOF packets. Calculate what range we should actually expect.
- Handle failures cleanly rather than panicking.
- Ensure that capture is stopped cleanly if test device access fails.
> HITL test fixes

- src/capture.rs
Using 16-bit deltas (2 bytes) in `CompactIndex` is a poor fit for nanosecond timestamp data, and causes the index to write a lot of blocks each time the delta range overflows, which also makes access inefficient. This is most noticeable when saving a capture, which requires reading all timestamps.
Using 24-bit deltas (3 bytes) works a lot better. I also tried 32-bit (4 bytes) but didn't see much difference in performance.
Fixes #169.
> Use 24-bit rather than 16-bit increments for timestamps.

- appimage/action.yml
- appimage/packetry.AppDir/usr/share/doc/libharfbuzz-gobject0/copyright
- appimage/packetry.AppDir/usr/share/doc/libharfbuzz-icu0/copyright
- appimage/packetry.AppDir/usr/share/doc/libharfbuzz-subset0/copyright
- appimage/packetry.AppDir/usr/share/doc/libharfbuzz0b/copyright
During packetry startup on Ubuntu `22.04.x` (and possibly others) the system will attempt to load `libharfbuzz` even though we are not linking to it directly, with the result that the system's version gets loaded instead:
```
openat(AT_FDCWD, "/tmp/.mount_packetjchMhG/usr/bin/../lib/libharfbuzz.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libharfbuzz.so.0", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
```
Because the version of `libharfbuzz` that ships with Ubuntu `22.04.x` is quite a lot older than the version of `libpango` we ship with the AppImage the following error results:
```
❯ ./packetry-x86_64.AppImage
/tmp/.mount_packetiCLpnp/AppRun.wrapped: symbol …
```
> Add libharfbuzz to Linux AppImage

- src/capture.rs
- src/compact_index.rs
- src/data_stream.rs
- src/index_stream.rs
- src/stream.rs
- src/ui.rs
Followup to #169 and #170.
Implements efficient iterators for our stream and index types, and uses them to iterate over timestamps and packets when saving a file.
For my test file of 371MB (3.5 million packets, 1.5 million transactions), this reduces save time from 4 seconds to 1.7 seconds, a speedup of **2.35x**.
This puts save speed almost on par with load speed.
> Implement iterators for our stream types, and use for faster saving

- src/backend/cynthion.rs
- src/backend/ice40usbtrace.rs
- src/backend/mod.rs
- src/backend/transfer_queue.rs
- src/test_cynthion.rs
- src/ui.rs
- src/usb.rs
- src/util.rs
This PR defines a common backend API for USB capture devices, and adds support for the [iCE40-usbtrace](https://gitea.osmocom.org/electronics/ice40-usbtrace) device.
The changes are made on top of a rebased version of #190. Tested with Cynthion only at this stage; @asdfuser and @smunaut, please test this with iCE40-usbtrace!
I have broken the changes to the `ice40usbtrace` backend down into as many commits as possible, so if I've broken anything hopefully it's easy to bisect. However, the final commit that ports everything to the new API is still a fairly big change.
The backend API is not very generic; it assumes that capture devices will work quite similarly to the two examples we currently have. That allows for sharing a lot of code, but means we might have to revisit the design in …
> Backend API and iCE40-usbtrace support

- src/ui.rs
Splits the stop_operation() function. The stop_operation() function itself is now only called when the stop button is pressed. It does not reset the UI state to "re-arm" for the next operation.
That work is instead moved to a new rearm() function, which is scheduled to be run on the UI thread once the load/save or capture thread completes.
> Fix STOP not being cleared after loading or saving a file.

- src/capture.rs
- src/decoder.rs
- src/item_widget.rs
- src/test_cynthion.rs
- src/ui.rs
- src/usb.rs
Allows the user to right click on a transfer, select "Save payload data...", choose a filename and save the payload.
> Add context menu system and options to save data

- src/capture.rs
- src/ui.rs
- src/usb.rs
- tests/emf2022-badge/devices-reference.txt
- tests/emf2022-badge/reference.txt
- tests/mouse/devices-reference.txt
- tests/mouse/reference.txt
- tests/split-enum/devices-reference.txt
- tests/ui/emf2022-badge/reference.txt
This PR adds some groundwork for supporting class-specific descriptors, where the meaning of the `bDescriptorType` depends on the context of the relevant interface class.
This is then used to identify and decode HID descriptors attached to an interface, where the interface class provides the context:
And to recognise requests for HID report descriptors, where the class of the recipient is known from previous traffic:
Note that HID report descriptors are not yet decoded or added to the device tree, that will come later.
> Initial support for HID descriptors

- .github/workflows/rust.yml
This adds the actions runner image version to the apt cache key, so it should get rebuilt when the runner is updated.
> actions: add runner version to apt cache key

- src/ui/mod.rs
Previously this would show redundant/mixed units like `123MiB / 456MiB bytes` and `123MiB / 456MiB packets`.
Now it shows `123MiB / 456MiB` and `123,456,789 / 456,789,123 packets`.
> Fix text shown in load/save progress bar.

- src/ui/tree_list_model.rs
In the `ListModel` interface, we must always report a `n_items()` that is consistent with the history of `items_changed` signals we have emitted.
So keep a published row count separately from our internal counts, and update it just before emitting an `items_changed` signal. Fixes crashes in GTK where the view gets out of sync with the model.
Initially triggered by #150, but I think it's possible for the crash to occur independently of that.
> Ensure that we don't change n_items() without an items_changed signal

- appimage/README.md
- appimage/docker/Dockerfile
- appimage/docker/patches/gtk-4.14.4-pin-fribidi.patch
- appimage/docker/patches/gtk-4.14.4-pin-gi-docgen.patch
- appimage/docker/patches/gtk-4.14.4-pin-libsass.patch
- appimage/docker/patches/gtk-4.14.4-pin-pango.patch
- appimage/docker/patches/gtk-4.14.4-pin-sysprof.patch
Recently, when appimage builds started to fail, it came to light that some of the sub-projects used by the gtk-4.14.4 source distribution were pointed at main branches.
Things began to break when the pango main branch dropped support for glib 2.76 in favor of 2.80.
This PR will apply patches during the docker image build that ensures all gtk-4.14.4 sub-projects use a fixed revision.
> Pin gtk-4.14.4 subproject revisions for appimage builds.

- .github/workflows/rust.yml
This disables rustup self-update on the Windows CI build to work around a weird issue with GitHub's runner described here: https://github.com/rust-lang/rustup/issues/3709
> ci: disable rustup self-update to workaround a Windows build issue

- .github/workflows/rust.yml
GitHub Actions runners have been updated to CMake 4.0.0, and this breaks some packages in our dependencies, which were locked to the 2024.05.24 vcpkg release.
There isn't a new vcpkg release with the fix yet, so this bumps us to the [commit](https://github.com/microsoft/vcpkg/commit/a1aebfa9d5eae7cf493e0a706b43915d687bb860) that fixed it, from https://github.com/microsoft/vcpkg/pull/44712.
> Update vcpkg to fix build failures with CMake 4.0.0 on runners.

- .gitignore
- src/capture.rs
- src/database/compact_index.rs
- src/database/data_stream.rs
- src/database/index_stream.rs
- src/database/stream.rs
- src/item.rs
- src/usb.rs
- src/util/dump.rs
- src/util/mod.rs
- src/util/vec_map.rs
This PR adds code to support dumping the capture database to disk, and restoring it back.
This is intended for debugging purposes only. The dump format is hierarchical, with data structures mapped to directories and files.
To verify that this works correctly, the `test_captures` test is modified to dump and restore the capture database in between decoding each capture and querying it for expected results.
> Add support for dumping & restoring capture database

- src/backend/ice40usbtrace.rs
- src/testing.rs
- src/ui/record_ui.rs
- src/usb.rs
- src/util/dump.rs
The paperclip demands we inline all our `format!` arguments. We shall obey. All hail the paperclip.
> Clippy fixes for Rust 1.88

- .github/workflows/rust.yml
This PR:
- Bumps vcpkg to the 2025-06-13 stable release.
- Fixes vcpkg caching by telling vcpkg to cache to files, then using `actions/cache@v4` to back up the file cache.
> Bump vcpkg to latest release and fix caching

- src/main.rs
- src/ui/device.rs
- src/ui/mod.rs
- src/ui/packetry.ui
- src/ui/window.rs
Up till now, the main window has been constructed programatically in the `activate` function.
This PR moves that code into a new `PacketryWindow` GObject class which subclasses GTK's `ApplicationWindow`.
The motivation here is that we want to set the initial positions of the horizontal and vertical pane separators to a sensible proportion of the initial window size. Currently we fudge this with some hardcoded minimum sizes in pixels. This has caused various frustrations discussed in #191.
By subclassing `ApplicationWindow`, we can override the `size_allocate` method. This seems to be the only way in GTK4 to consistently be notified when the window size is first known.
With that method hooked, we can set the initial size of the traffic pane to 75% of the initial window size both …
> Reimplement main window as a subclass with UI loaded from file

- .github/workflows/rust.yml
The latest `cargo-license` release [0.7.0](https://crates.io/crates/cargo-license/0.7.0) requires Rust 1.86.
We test with our MSRV which is currently 1.83, so that failed with the new crate.
Fixed by pinning `cargo-license` to 0.6.
To avoid similar issues in future I have locked the versions of `cargo-wix` and `cargo-all-features` as well.
Also took the opportunity to cache the `cargo-all-features` install.
> CI: Lock cargo subcommands to specific versions

- src/ui/device.rs
Fixes #257.
Calling `StringList::splice` to replace all its strings does not cause the `DropDown` using it to emit a selection change. Instead, make a whole new `StringList`.
> Replace StringList when updating a dropdown, rather than splicing

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/ui/mod.rs
- src/ui/settings.rs
- src/ui/window.rs
- wix/manual-licenses/LICENSE-ndk-context-0.1.1.txt
- wix/rust_licenses.py
Fixes #177.
Uses the [preferences](https://docs.rs/preferences/latest/preferences/index.html) crate to store settings in an OS-appropriate, user-specific location, in JSON format. On Linux for instance, settings are stored in `~/.config/Packetry/settings.prefs.json`.
Initially the only field is a `last_used_directory` which is retained across file chooser dialogs; other fields can be added later as needed.
> Remember last used directory

- Cargo.lock
- Cargo.toml
- src/ui/mod.rs
- src/ui/window.rs
- wix/rust_licenses.py
Adds an option to the main menu which dumps the complete database state into a `zip` file for debugging.
Among other scenarios, this should be helpful in a case such as #213 where the capture cannot be saved normally.
> Add the capability to dump the database from the UI

- .github/workflows/rust.yml
This is no longer included by default with Rust 1.90.
> CI: Explicitly install cargo-clippy component with toolchain.

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- docs/source/quick_start.rst
- src/backend/cynthion.rs
- src/backend/ice40usbtrace.rs
- src/backend/mod.rs
- src/testing.rs
- src/ui/device.rs
- src/ui/mod.rs
- src/ui/power.rs
- src/ui/window.rs
- wix/manual-licenses/LICENSE-logwise_proc-0.1.1.txt
We're still doing a fair bit of blocking IO from the UI thread.
In practice this hasn't generally been an issue since everything normally responds quickly.
However, it sometimes feels laggy, and working around https://github.com/kevinmehall/nusb/issues/149 is going to require adding some deliberate delays during hotplugging.
So, let's do this properly.
- Convert all functions that do blocking nusb IO to `async`.
- Either run async functions with [`block_on`](https://docs.rs/futures-lite/latest/futures_lite/future/fn.block_on.html) in a dedicated thread, or integrate them into the GTK main loop by spawning them with [`glib::spawn_future_local`](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/fn.spawn_future_local.html).
- Enable the `smol` feature of `nusb` to support usage with …
> Convert all blocking USB IO to async

- src/backend/cynthion.rs
- src/backend/ice40usbtrace.rs
- src/backend/mod.rs
Workaround for https://github.com/kevinmehall/nusb/issues/149.
When hotplugging a device on Windows, if claiming the necessary interface fails, wait 50ms and retry up to 5 times.
> Fix "Failed to claim interface" error when hotplugging a device on Windows
