.github/workflows/rust.yml
src/capture.rs
src/decoder.rs
src/expander/mod.rs
src/hybrid_index.rs
src/usb.rs

This sets up GitHub actions to build & test any pushes or PRs. An example run can be seen here: https://github.com/miek/packetry/actions/runs/2339638314
It also adds a [Clippy](https://github.com/rust-lang/rust-clippy#clippy) pass, which has a bunch of lints to check for style etc. I think the suggestions are pretty good (e.g: https://github.com/miek/packetry/runs/6453987836?check_suite_focus=true), though I did squelch a few where I think it made more sense to break the rules for code clarity or to match USB spec naming.

Setup GitHub Actions

---

.github/workflows/rust.yml
src/backend/luna.rs
src/main.rs

In conjunction with https://github.com/greatscottgadgets/luna/pull/197 which adds this control to the gateware, add a dropdown to the UI to select the capture speed.

Add capture speed selection to UI

---

src/usb.rs

Clippy fixes

---

src/ui.rs

This PR switches the scrollable elements of the UI from the `ListView` to the `ColumnView` widget.
Currently there is only a single column for each of the Traffic and Devices views, but making this change enables us to later add timestamps and other fields in separate columns.
The magic we were missing when trying to do this before was the `data-table` CSS class, which makes the column view render similarly to the list view rather than injecting lots of padding.
Closes #7

Switch from `ListView` to `ColumnView`

---

src/usb.rs

Shut up, you tedious paperclip.

Clippy fix

---

CHANGELOG.md
Cargo.toml

This PR:
* Adds a CHANGELOG.md file to the repo.
* Updates the crate metadata.
Note: I was at a bit of a loss when it came to finding much that fit the `keywords` field in the crate metadata -- the full list is here https://crates.io/category_slugs !

Pre-release chores

---

Cargo.toml

Explains all the optional features and how they can be used for debugging and testing.

Document the available build features

---

README.md

Add note to README about optional features

---

.github/workflows/rust.yml
Cargo.toml
src/ui.rs

This had gotten broken due to the switch to using `gio::File` instead of `PathBuf`.

Fix building with `record-ui-test` feature

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
README.md
src/main.rs
wix/manual-licenses/LICENSE-dark-light-1.1.1.txt
wix/manual-licenses/LICENSE-malloc_buf-0.0.6.txt
wix/rust_licenses.py

Uses:
- Rust [dark-light](https://github.com/frewsxcv/rust-dark-light) crate to detect the system setting
- GtkSettings [set_gtk_application_prefer_dark_theme](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.Settings.html#method.set_gtk_application_prefer_dark_theme) to configure the GTK behaviour.  
Closes #121.

Select dark theme if detected as a system preference.

---

docs/source/user_interface.rst

also document both functions of Stop button

Document clearing of Traffic and Device panes

---

src/ui.rs

Fix open button not being re-enabled after stop

---

Cargo.lock

Update yanked dependencies bytemuck v1.16.0 and futures-util v0.3.30

---

src/database/compact_index.rs
src/database/data_stream.rs
src/database/index_stream.rs
src/ui/item_widget.rs
src/ui/record_ui.rs
src/usb.rs

One day we will be victorious over the insatiable paperclip!

Clippy fixes for 1.85.0

---

src/capture.rs
src/item.rs
src/ui/mod.rs
src/ui/record_ui.rs
src/usb.rs

More nitpicks for our paperclip-shaped friend.
In the process, I found a [bug in clippy](https://github.com/rust-lang/rust-clippy/issues/14531) !

Additional clippy fixes.

---

src/backend/cynthion.rs
src/backend/ice40usbtrace.rs
src/backend/mod.rs
src/main.rs
src/testing.rs
src/ui/device.rs
src/ui/mod.rs
src/ui/packetry.ui
src/ui/power.rs
src/ui/window.rs

This PR adds control of the target power supply when using a Cynthion USB analyzer.
Requires analyzer gateware changes from https://github.com/greatscottgadgets/cynthion/pull/243.
Stacked on #239.

Power control

---

.github/workflows/rust.yml

Hoping this will fix our caching issues...

Use vcpkg-cache action instead of manual use of actions/cache

---

Cargo.lock
src/file.rs
src/ui/item_widget.rs
src/usb.rs
src/util/dump.rs

O wise paperclip, please accept these offerings and bless our code once more...

Clippy fixes for Rust 1.89

---

.github/workflows/rust.yml
src/fuzzer.rs

This PR fixes the fuzzer build and adds it to CI, testing 10000 inputs from a fixed seed.

Fix fuzzer and add to CI

---

wix/manual-licenses/LICENSE-ndk-context-0.1.1.txt

Just spotted something very obviously wrong in the diff for #256 :)

Correct license file for ndk-context 0.1.1
